# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('lastname', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=10)),
                ('selfi', models.ImageField(upload_to='upload/')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='date cheek')),
            ],
        ),
    ]
