# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 09:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('singup', '0010_auto_20170403_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('aboutnow', models.CharField(max_length=200)),
                ('post_date', models.DateField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='singup.users')),
            ],
        ),
    ]
