# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 16:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('singup', '0011_auto_20170411_1545'),
        ('space', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cheekin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.DecimalField(decimal_places=16, max_digits=20)),
                ('y', models.DecimalField(decimal_places=16, max_digits=20)),
                ('cheek_date', models.DateTimeField(auto_now_add=True, verbose_name='date cheek')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='singup.users')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
