# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 16:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0002_auto_20170412_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='name',
        ),
    ]
