# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 09:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0004_messages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='fromUser',
            new_name='toUser',
        ),
    ]
