# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 16:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0006_messages_fromuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cheekin',
            new_name='Checkin',
        ),
        migrations.RenameModel(
            old_name='messages',
            new_name='Message',
        ),
    ]
