# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='selfi',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
