# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singup', '0006_auto_20170402_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='selfi',
            field=models.ImageField(upload_to='upload', verbose_name='img'),
        ),
    ]
