# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singup', '0010_auto_20170403_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
