# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 16:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('singup', '0012_users_start_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='users',
            new_name='User',
        ),
    ]
